import {
  LayoutDashboard,
  Users,
  Image as ImageIcon,
  Plus,
  Zap,
  Download,
  Loader2,
  Trash2,
  MoreVertical,
  Settings,
  Grid,
  History,
  CheckCircle2,
  Upload,
  X,
  Sun,
  Moon,
  CreditCard,
  Bell,
  Shield,
  FileText,
  Check
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Characters: Users,
  Scenes: ImageIcon,
  Create: Zap,
  Plus: Plus,
  Download: Download,
  Spinner: Loader2,
  Trash: Trash2,
  More: MoreVertical,
  Settings: Settings,
  Gallery: Grid,
  History: History,
  Check: CheckCircle2,
  Upload: Upload,
  X: X,
  Sun: Sun,
  Moon: Moon,
  CreditCard: CreditCard,
  Bell: Bell,
  Shield: Shield,
  FileText: FileText,
  CheckMark: Check,
  Zap: Zap
};